// main.js - Funciones compartidas
const API_URL = 'http://localhost:3000/favorites';

async function isFavorite(type, id) {
    try {
        const response = await fetch(API_URL);
        const favorites = await response.json();
        return favorites.some(fav => fav.type === type && fav.originId === id);
    } catch (error) {
        console.error('Error checking favorite:', error);
        return false;
    }
}

async function toggleFavorite(type, id, name, img, button) {
    try {
        const response = await fetch(API_URL);
        const favorites = await response.json();
        // Find by type and the original resource ID (originId)
        // Convert both to numbers for proper comparison
        const numId = typeof id === 'string' ? parseInt(id) : id;
        const existingFav = favorites.find(fav => fav.type === type && parseInt(fav.originId) === numId);

        if (existingFav) {
            // Eliminar
            // Use the 'id' generated by json-server for deletion
            await fetch(`${API_URL}/${existingFav.id}`, { method: 'DELETE' });
            button.textContent = '🤍 Añadir';
            button.classList.remove('favorited');
        } else {
            // Añadir
            // We use 'originId' to store the original resource ID,
            // letting json-server generate its own primary 'id'.
            const favToSave = { type, originId: numId, name, img };

            await fetch(API_URL, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(favToSave)
            });

            button.textContent = '❤️ Quitado';
            button.classList.add('favorited');
        }
    } catch (error) {
        console.error('Error toggling favorite:', error);
        alert('Error al actualizar favoritos. Asegúrate de que el servidor json-server esté corriendo.');
    }
}

async function removeFavorite(dbId) {
    try {
        await fetch(`${API_URL}/${dbId}`, { method: 'DELETE' });
        location.reload();
    } catch (error) {
        console.error('Error removing favorite:', error);
    }
}